FROM --platform=linux/riscv64 debian:trixie


RUN apt-get update && \
    apt-get install -y dpkg-dev && \
    sed -i 'p;s/^deb /deb-src /' /etc/apt/sources.list || true


RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    devscripts \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
